Ecommerce/Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
]

Ecommerce/home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

bucket_urls = [
    path('', views.BucketHome.as_view(), name='bucket'),
    path('delete_obj_bucket/<str:object_key>', views.BucketDeleteObject.as_view(), name='bucket_delete_object'),
    path('download_obj_bucket/<str:object_key>', views.BucketDownloadObject.as_view(), name="bucket_download_object"),
    #TODO:  path('upload_obj_bucket/<str:object_key>', views.BucketUploadView.as_view(), name="bucket_upload_object"),
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>', views.HomeView.as_view(), name='category_filter'),
    path('bucket/', include(bucket_urls)),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
]

Ecommerce/orders/urls.py
from django.urls import path
from . import views 

app_name = 'orders'

urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('order_detail/<int:order_id>', views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>', views.CartRemoveView.as_view(), name='cart_remove'),
    path('cart/remove_all/', views.CartRemoveAllView.as_view(), name="cart_remove_all"),
    path('pay/<int:order_id>', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
    path('apply/<int:order_id>', views.CouponApplyView.as_view(), name='coupon_apply'),
]

Ecommerce/home/models.py
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField


class Category(models.Model):
    sub_category = models.ForeignKey('self', on_delete=models.CASCADE, related_name='scategory', null=True, blank=True)
    is_sub = models.BooleanField(default=False)
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    
    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'categories'
        verbose_name = 'category'
        
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("home:category_filter", args=[self.slug,])
    


class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='products')
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField()
    description = models.RichTextField()
    price = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('name',)
        
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("home:product_detail", args=[self.slug,])
    
    
    

Ecommerce/home/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .models import Product, Category
from . import tasks
from django.contrib import messages
from utils import IsAdminMixins
from orders.forms import CardAddForm


class HomeView(View):
    
    def get(self, request, category_slug=None):
        products = Product.objects.filter(available=True)
        categories = Category.objects.filter(is_sub=False)
        if category_slug:
            category = Category.objects.get(slug=category_slug)
            products = products.filter(category=category)
        return render(request, 'home/home.html', {
            'products': products,
            'categories': categories,
        })


class ProductDetailView(View):
    
    def get(self, request, slug):
        form = CardAddForm
        product = get_object_or_404(Product, slug=slug)
        return render(request, 'home/detail.html', {
            'product': product,
            'form': form,
        })
        
        
class BucketHome(IsAdminMixins, View):
    template_name = 'home/bucket.html'
    
    
    def get(self, request):
        objects = tasks.get_obj_list_task()
        return render(request, self.template_name, {
            'objects': objects,
        })
        
        
class BucketDeleteObject(IsAdminMixins, View):
    
    def get(self, request, object_key):
        tasks.delete_object_task(object_key) # tasks.delete_object_task.delay(object_key)
        messages.success(request, 'deleted successfully', 'success')
        return redirect('home:bucket')
    
    
class BucketDownloadObject(IsAdminMixins, View):
    
    def get(self, request, object_key):
        tasks.download_object_task(object_key) # tasks.download_object_task.delay(object_key)
        messages.success(request, 'downloaded successfully', 'success')
        return redirect('home:bucket')
        
'''
TODO:

class BucketUploadView(View):
    
    def get(self, request, object_key):
        tasks.upload_object_task(object_key)
        messages.success(request, 'uploaded successfully', 'success')
        return redirect('home:bucket')
'''

Ecommerce/home/templates/home/bucket.html
{% extends 'base.html' %}


{% block content %}

<div class="table-responsive">
    <table class="table">
    <caption>Bucket objects</caption>

    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Size</th>
        <th scope="col">Download</th>
        <th scope="col">Delete</th>
        <th scope="col">Upload</th>
      </tr>
    </thead>
    
    <tbody>
      {% for object in objects %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ object.key }}</td>
        <td>{{ object.size|filesizeformat }}</td>
        <td><a href="{% url 'home:bucket_download_object' object.key %}">Download</a></td>
        <td><a href="{% url 'home:bucket_delete_object' object.key %}">Delete</a></td>
        {% comment %}
        <td><a href="{% url 'home:bucket_upload_object' object.key %}">Upload</a></td>
        {% endcomment %}
      </tr>
      {% endfor %}
    </tbody>

  </table>
  </div>

{% endblock %}

Ecommerce/home/templates/home/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ product.name }}</h1>
    <small>{{product.price}} Toman</small></br>
    <img src="{{ product.image.url }}" height="300" width="300" alt="">
    <p>{{ product.description }}</p>

    <form action="{% url 'orders:cart_add' product.id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Add">
    </form>
{% endblock %}

Ecommerce/home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}


{% block extra_headers %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}


{% block content %}

{% for category in categories %}


    <div class="btn-group">
        <a href={{category.get_absolute_url }} class="btn btn-danger">{{ category.name }}</a>
        <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
        <span class="visually-hidden">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu">
            {% for sub in category.scategory.all %}
                <li><a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
    
{% endfor %}

</br></br></br>

{% for product in products %}
    <div class="card" style="width: 18rem; display:inline-block;">
        <img class="card-img-top" src="{{product.image.url}}">
        <div class="card-body">
        <h5 class="card-title">{{ product.name }}</h5>
        <p class="card-text">{{ product.description }}</p>
        <a href="{{ product.get_absolute_url }}" class="btn btn-primary">Detail</a>
        </div>
    </div>
{% endfor %}
{% endblock %}